//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nvprojet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class administrateur
    {
        public int id { get; set; }
        [Required(ErrorMessage ="champ obligatoire!!!!")]
        public string nom { get; set; }
        [Required(ErrorMessage = "champ obligatoire!!!!")]
        public string prenom { get; set; }
        [Display(Name = "login")]
        [Required(ErrorMessage = "champ obligatoire!!!!")]
        public string logn { get; set; }
        [Display(Name = "password")]
        [Required(ErrorMessage = "champ obligatoire!!!!")]
        public string passwd { get; set; }
    }
}
