//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nvprojet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class autocar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public autocar()
        {
            this.trajets = new HashSet<trajet>();
        }
    
        public int id { get; set; }
        [Display(Name="libelle")]
       [Required(ErrorMessage ="champ obligatoire!!!!!")]
       
        public string libele { get; set; }
      [Required(ErrorMessage = "champ obligatoire!!!!!")]
        public string marque { get; set; }
       [Required(ErrorMessage = "champ obligatoire!!!!!")]
        public Nullable<bool> wifi { get; set; }
        [Required(ErrorMessage = "champ obligatoire!!!!!")]
        [Display(Name = "Nombre de place")]
        public Nullable<int> Nbr_place { get; set; }
       // [Required(ErrorMessage = "champ obligatoire!!!!!")]
        [Display(Name = "image")]
        public string img { get; set; }
       
        public Nullable<int> id_ste { get; set; }
        [Display(Name = "nom societe")]
        public virtual societe societe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trajet> trajets { get; set; }
    }
}
