//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nvprojet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.abennements = new HashSet<abennement>();
            this.demandes = new HashSet<demande>();
        }
    
        public int id { get; set; }
        [Display(Name="nom ")]
        [Required(ErrorMessage ="champ obligatoire!!!!")]
        public string nom_cli { get; set; }
        [Display(Name = "Prenom ")]
        [Required(ErrorMessage = "champ obligatoire!!!!")]
        public string prenom_cli { get; set; }
        [Display(Name = "Adresse ")]
        [Required(ErrorMessage = "champ obligatoire!!!!")]
        public string adresse { get; set; }
        [Display(Name = "Telephone ")]
        [Required(ErrorMessage = "champ obligatoire!!!!")]
        public Nullable<int> tel { get; set; }
        [Display(Name = "login")]
        [Required(ErrorMessage = "champ obligatoire!!!!")]
        public string login_cli { get; set; }
        [Display(Name = "mot de passe")]
        [Required(ErrorMessage = "champ obligatoire!!!!")]
        public string mdp { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "champ obligatoire!!!!")]
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<abennement> abennements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<demande> demandes { get; set; }
    }
}
