//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nvprojet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class societe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public societe()
        {
            this.autocars = new HashSet<autocar>();
        }
    
        public int id { get; set; }
        [Display(Name="Nom societe")]
        [Required(ErrorMessage ="champ obligatoire!!!!")]
        public string nom_s { get; set; }
        [Required(ErrorMessage = "champ obligatoire!!!!")]
        public string siege { get; set; }
        [Required(ErrorMessage = "champ obligatoire!!!!")]
        public Nullable<int> pattente { get; set; }
        [Required(ErrorMessage = "champ obligatoire!!!!")]
        public string fix { get; set; }
        [Required(ErrorMessage = "champ obligatoire!!!!")]
        public string fax { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "champ obligatoire!!!!")]
        public string email_s { get; set; }
        [Required(ErrorMessage = "champ obligatoire!!!!")]
        [Display(Name = "login")]
        public string logn_s { get; set; }
        [Display(Name = "password")]
        [Required(ErrorMessage = "champ obligatoire!!!!")]
        public string passwd_s { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<autocar> autocars { get; set; }
    }
}
