//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nvprojet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class trajet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trajet()
        {
            this.abennements = new HashSet<abennement>();
        }
    
        public int id { get; set; }
        [Display(Name="ville départ")]
        [Required(ErrorMessage ="champ obligatoire!!!!!")]
        public string ville_depart { get; set; }
        [Display(Name = "ville arrriver")]
        [Required(ErrorMessage = "champ obligatoire!!!!!")]
        public string ville_arriver { get; set; }
        [Display(Name = "heure départ")]
        [Required(ErrorMessage = "champ obligatoire!!!!!")]
        public string heure_dep { get; set; }
        [Display(Name = "heure arrriver")]
        [Required(ErrorMessage = "champ obligatoire!!!!!")]
        public string heur_arv { get; set; }
        public Nullable<int> id_aut { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<abennement> abennements { get; set; }
        public virtual autocar autocar { get; set; }
    }
}
